add_newline = true
format = "$username$hostname$directory$git_branch$git_state$git_status$git_metrics$cmd_duration$line_break$python$nix_shell$direnv$character"

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"
vicmd_symbol = "[❮](bold green)"

[cmd_duration]
format = "[$duration]($style) "
min_time = 2000
style = "yellow"

[directory]
read_only = " !"
style = "bold blue"
truncation_symbol = "…/"

[git_branch]
format = "[$branch]($style) "
style = "242"

[git_state]
format = "([$state( $progress_current/$progress_total)]($style)) "
style = "bright-black"

[git_status]
ahead = "⇡$count "
behind = "⇣$count "
conflicted = "= "
deleted = "✘ "
diverged = "⇕⇡$ahead_count⇣$behind_count"
format = "([$all_status$ahead_behind]($style) )"
modified = "! "
renamed = "» "
staged = "+ "
stashed = "≡ "
style = "bold purple"
untracked = "? "

[hostname]
format = "[$hostname]($style) "
ssh_only = false
style = "bold dimmed green"

[nix_shell]
format = "[$symbol]($style) "
style = "bold blue"
