name: Update Dotfiles Structure

on:
  push:
  pull_request:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-structure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tree
        run: sudo apt-get install -y tree

      - name: Generate tree structure
        run: |
          echo "# ðŸ“‚ Dotfiles Structure" > structure.md
          echo '```' >> structure.md
          tree -L 3 --noreport >> structure.md
          echo '```' >> structure.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "automated: update structure.md"
          branch: nixos
          file_pattern: structure.md
          commit_user_name: "Readme Bot"
          commit_author: "Readme Bot <actions@github.com>"
          skip_dirty_check: false
          skip_fetch: false
          push_options: '--force'
